version: '3.4'

services:
  service.basket.api:
    container_name: service-basket-api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=5001
    ports:
      - "5001:5001"
    networks:
      - server-internal-net

  service.catalog.api:
    container_name: service-catalog-api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=5002
    ports:
      - "5002:5002"
    networks:
      - server-internal-net

  apigateway.yarp.reverseproxy:
    container_name: apigateway-yarp-reverseproxy
    depends_on:
      - service.basket.api
      - service.catalog.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=7300
    ports:
      - "7300:7300"
    networks:
      - server-internal-net

networks:
  server-internal-net:
    driver: bridge