version: '3.4'

services:
  service.basket.api:
    image: ${DOCKER_REGISTRY-}servicebasketapi
    build:
      context: .
      dockerfile: src/Services/Baskets/Service.Basket.API/Dockerfile

  service.basket.api.2:
    image: ${DOCKER_REGISTRY-}servicebasketapi
    build:
      context: .
      dockerfile: src/Services/Baskets/Service.Basket.API/Dockerfile

  service.catalog.api:
    image: ${DOCKER_REGISTRY-}servicecatalogapi
    build:
      context: .
      dockerfile: src/Services/Catalogs/Service.Catalog.API/Dockerfile


  apigateway.yarp.reverseproxy:
    image: ${DOCKER_REGISTRY-}apigatewayyarpreverseproxy
    build:
      context: .
      dockerfile: src/ApiGateways/ApiGateway.YARP.ReverseProxy/Dockerfile

